import type { Metadata } from 'next';

import { Inter } from 'next/font/google';

import './globals.css';

import { MainLayout } from '../layouts/MainLayout';
import { Client } from './_components/Client';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const theme = 'dark';
  return (
    <html lang="en" className={theme} data-theme={theme}>
      <body className={inter.className}>
        <MainLayout theme={theme}>
          <Client />
          {children}
        </MainLayout>
      </body>
    </html>
  );
}
